//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtnEtn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> Car { get; set; }
        public System.DateTime ConDate { get; set; }
    
        public virtual Car Car1 { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
